on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: create testdata
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: install audio tools
        run: |
          sudo apt-get update
          sudo apt-get -y install espeak ffmpeg

      - name:
        run: |
          ./mktestdata.sh --dir ./sd
          cd sd && zip -r ../testdata.zip *

      - name: upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: assets
          path: testdata.zip
