on:
  release:
    types: [created]

name: create testdata and upload assets
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: install audio tools
        run: |
          sudo apt-get update
          sudo apt-get -y install espeak ffmpeg

      - name:
        run: ./mktestdata.sh --dir ./sd

      - name: Upload release assets
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: './sd/*'
